import { getEnv } from "../utils/env";

// constants/env.js
export const ENV = {
  FIREBASE: {
    API_KEY: getEnv("VITE_FIREBASE_API_KEY"),
    AUTH_DOMAIN: getEnv("VITE_FIREBASE_AUTH_DOMAIN"),
    PROJECT_ID: getEnv("VITE_FIREBASE_PROJECT_ID"),
    STORAGE_BUCKET: getEnv("VITE_FIREBASE_STORAGE_BUCKET"),
    MESSAGING_SENDER_ID: getEnv("VITE_FIREBASE_MESSAGING_SENDER_ID"),
    APP_ID: getEnv("VITE_FIREBASE_APP_ID"),
    MEASUREMENT_ID: getEnv("VITE_FIREBASE_MEASUREMENT_ID"),
  },
  CURRENCYAPI: {
    API_KEY: getEnv("VITE_CURRENCYAPI_API_KEY"),
  },
};
